language: node_js

node_js:
  - node

install:
  - npm install -g firebase-tools
  - cd public
  - bower install
  - cd ..

script:
  - echo "Deploying..."
  
after_success:
  - firebase deploy - project intcreator-1551e - token $FIREBASE_TOKEN