language: node_js

node_js:
  - node

before_install:
  - npm i -g polymer-cli

install:
  - cd public
  - npm install

script:
  - polymer build
  - cd ..

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN